const getBackgroundList =()=>{
    return['<i id="shapes" class="fa fa-circle"></i>',
           '<i id="shapes" class="fa fa-square"></i>',
           '<i id="shapes" class="fas fa-ring"></i>',
           '<i id="shapes" class="fa fa-certificate"></i>',
           '<i id="shapes" class="fa fa-cloud"></i>',
           "<i id='shapes' class='fa fa-comment'></i>",
           "<i id='shapes' class='fa fa-heart'></i>",
           "<i id='shapes' class='fa fa-file'></i>",
           "<i id='shapes' class='fa fa-comment-alt'></i>",
           "<i id='shapes' class='fas fa-hand-rock'></i>",
           "<i id='shapes' class='fas fa-shield-alt'></i>",
           "<i id='shapes' class='fas fa-star-of-life'></i>",
           "<i id='shapes' class='fa fa-superpowers'></i>",
           "<i id='shapes' class='fa fa-circle-o-notch'></i>",
           "<i id='shapes' i class='fa fa-circle-thin'></i>",
           "<i id='shapes' class='fa fa-circle-o'></i>",
           "<i id='shapes' class='fa fa-comment-o'></i>",
           "<i id='shapes' class='fa fa-crosshairs'></i>",
           "<i id='shapes' class='fa fa-heart-o'></i>",
           "<i id='shapes' class='fa fa-lemon-o'></i>",
           "<i id='shapes' class='fa fa-mobile'></i>",
           "<i id='shapes' class='fa fa-recycle'></i>",
           "<i id='shapes' class='fa-solid fa-crop-simple'></i>",
           "<i id='shapes' class='fas fa-vector-square'></i>",
];
}